Fix compile error if Qt5QuickCompiler... and Qt5LinguistTools are installed at the same time Fix license verify code Update translation file content Add missing translatable string Add more German translations Fix polished loop error Fix undefined reference to showLaunchError improve the availability of the versionslist Fix google play latest not working,... ...after selecting an foreign architecture https://github.com/ChristopherHX/mcpelauncher-ui-manifest/issues/15 Fix downloading older versions for every... architecture. Remove useless error message. https://github.com/ChristopherHX/mcpelauncher-ui-manifest/issues/15